### ISSUE TITLE
We should have units for indicators.

### ISSUE THREAD

**Issue by tnagorra** [dfid-dvs/server#10]
All travel time: Hours
All precipitation: mm/month
All Incidence / Prevalence / Severity : Percentages
the units for the Pop Density layer are Persons/sq 100m

### Proposed Api schema for an indicator
```js
{
      "id": 15,
      "fullTitle": "2011 Mean International Wealth Index (IWI)",
      "abstract": "...",
      "federalLevel": "palika level",
      "isCovid": false,
      "unit": "hours", // "mm/month", "%", "persons/sq 100m", null
      "datatype": "float", // "integer"
}
```

**Comment by metalica20** [comment]
For this we are waiting for robert response to provide the unit

**Comment by tnagorra** [comment]
I have updated Robert's message on the description and sent an excel sheet with some indicators in slack.
