### ISSUE TITLE
Error in aggregation for "Households heavily affected by COVID restrictions"

### ISSUE THREAD

**Issue by tnagorra** [dfid-dvs/server#30]
Households affected in Pokhara Lekhnath (metropolitan city) is greater than Kaski (district)

![image](https://user-images.githubusercontent.com/4928045/80805470-dcfcb580-8bd7-11ea-97f5-58b88a3685a3.png)

![image](https://user-images.githubusercontent.com/4928045/80805487-edad2b80-8bd7-11ea-9727-52d32c073323.png)

**Comment by tnagorra** [comment]
This was fixed, right @metalica20 ?

**Comment by metalica20** [comment]
yes in development server @tnagorra
